### PR TITLE
datatable and list behaviors

### PR DESCRIPTION
**Pull request by redref**
Hi,

I was digging on your last commit and kinda rollbacked it (sorry). Need your thoughts on this, and feel free to trash it.

This new version of "lists.js" provide cross-reload filtering and fix your concern (metrics page) by adding an explicit hide flag.

I also fixed footer margin with the same unit as footer height (1em padding + 1.2em line height => 4em footer padding).

WIP :
Implement fact/<fact_name> into datatables component, I was working on inventory page on my side (which is kinda the same values and endpoint)
Right now, I'm stuck with paging as facts/facts-contents endpoint does not handle 'value' ordering.

### CODE REVIEW

**Comment by mterzo** [comment]
That's fine. Im not a front end guy.  Just want things to work.

**Comment by redref** [comment]
For the record, we have "filter-table" on 
facts
fact
catalog
catalog_compare
catalogs
inventory
nodes

My plan was to move all these to paging feature but I was way ahead real commits. I really missed the elephant when deleting tables.js.

I'm fine with this going back then and will submit page per page modifications.

**Comment by mterzo** [comment]
I think I rushed you on the other commit. And we commuted to early by mistake.

**Comment by redref** [comment]
Think this is ready to merge.

Do you prefer me to make separates PR's on footer padding and non-needed columns argument ?

**Comment by mterzo** [comment]
Haven't had to chance to try it out yet.  The PR I associated this with has a bunch of HTML / JS updates so this one PR is fine.

**Pull request merged**
